More robust.
git-svn-id: https://svn.pnl.gov/svn/hpcgroup/projects/modsim-tools@14911 4c623a4d-1e8e-0410-8a3e-ee3132d44425

diff --git a/make-batch-job/freq-unset b/make-batch-job/freq-unset
--- a/make-batch-job/freq-unset
+++ b/make-batch-job/freq-unset
@@ -9,13 +9,26 @@
 
 me=`basename $0`
 
-hostname=`hostname`
+info="${me}[$(hostname)]:"
 
-info="${me}:${hostname}:"
+#****************************************************************************
 
-for b in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor ; do
-    echo ondemand  > $b;
+sys_cpu_gov=/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
+sysglob_cpu_gov=/sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
+
+#****************************************************************************
+
+if [[ ! -w "${sys_cpu_gov}" ]] ; then
+    echo "*** Error: ${info} Cannot write '${sys_cpu_gov}'!"
+    exit 1
+fi
+
+for x in ${sysglob_cpu_gov} ; do
+    echo ondemand > $x;
 done
 
-printf "${info} restoring CPU 'dynamic turbo'. Governor says: " && \
-    cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor | uniq
+#****************************************************************************
+
+info_gov=$( cat ${sysglob_cpu_gov} | uniq )
+
+printf "${info} restoring CPU 'dynamic turbo'. Governor: ${info_gov}\n"
